version: 2

models:
  - name: sales
    description: sales has a record for each customer, order, product combination
    columns:
      - name: Line ID
        description: unique value for each line
        tests:
          - unique
          - not_null
      - name: Customer ID
        description: unique ID for a customer
      - name: Order ID
        description: order id
        meta:
          glean:
            aggregationOptions:
              binsEnabled: false
      - name: Line Number
        description: which line number; values from 1 to 5
        meta:
          glean:
            aggregationOptions:
              defaultBinWidth: 1
              binsEnabled: false
      - name: Product ID
        description: allows us to join to the products table
      - name: Order Value
        description: order value - this is just for this line
        meta:
          glean:
            aggregationOptions:
              defaultBinWidth: 0.5
              binsEnabled: false
      - name: Quantity
        description: number of pizzas
        meta:
          glean:
            aggregationOptions:
              defaultBinWidth: 1
              binsEnabled: false
      - name: Timestamp
        description: the time the order was created
    config:
      meta:
        glean:
          cols:
            - id: row_count
              type: metric
              name: Pizza Orders
              aggregate: row_count

  - name: orders
    description: order information
    columns:
      - name: Order ID
        description: order id
        meta:
          glean:
            aggregationOptions:
              binsEnabled: false
            primaryKey: true
      - name: Payment Method
        description: credit or cash
      - name: Delivery
        description: boolean, is it delivery
      - name: Type
        description: whether the order is a subscription order 
    config:
        meta:
          glean:
            cols:
              - id: row_count
                type: metric
                name: Pizza Orders
                aggregate: row_count

  - name: products
    description: order information
    columns:
      - name: Product ID
        description: the unique identifier of the product
        meta:
          glean:
            primaryKey: true
      - name: Pizza Size
        description: pizza size; small, medium or large
      - name: Pizza Type
        description: the type of pizza
      - name: Price
        description: price in USD per pizza
        meta:
          glean:
            aggregationOptions:
              defaultBinWidth: 1
              binsEnabled: true
    config:
        meta:
          glean:
            cols:
              - id: row_count
                type: metric
                name: Product Count
                aggregate: row_count
