name: 'dbt_proj'
version: '1.0.0'
config-version: 2

profile: 'duckdb_profile'

model-paths: ["models"]

clean-targets:
- "target"
- "dbt_packages"

models:
  # configure everything to be materialized as parquet
  +materialized: external
  +meta:
    glean-defaults:
      glean: "1.0"
      preventUpdatesFromUI: false
      source:
        connectionName: Uploads
